// AUTO-GENERATED by tools/gen_ts_sdk.py ← schemas/mcp-tools.json —— 禁止手改
// 单一真相源 = schemas/mcp-tools.json(78 工具;改契约后重跑生成器,--check 拦漂移)
// 传输面:POST /api/v1/tools/<tool>(册七 T7.1/ADR-0025)+ GET /api/v1/events 订阅;
// 零依赖:全局 fetch + 手写 SSE 解析(浏览器 / node >=18 / bun 通用)。
/* eslint-disable */


/** 结果协议 envelope(所有工具/别名端点的统一返回;HTTP 状态码由 code 确定性映射)。 */
export interface Envelope<T = Record<string, unknown>> {
  ok: boolean;
  code: string;
  ns: string;
  message: string;
  data: T;
}

/** 工具入参兜底形(泛型逃逸口;类型化方法见下方按工具生成的面)。 */
export type ToolArgs = Record<string, unknown>;

/** /api/v1/events 的一帧(SSE data 负载;ok/code/event/seq 老字段齐)。 */
export interface WorkspaceEvent {
  ok: boolean;
  code: string;
  event: string;
  seq: number;
  paths?: string[];
  kind?: string;
  runId?: string;
  state?: string;
  [k: string]: unknown;
}

export interface CutforgeOptions {
  /** 服务基址,如 http://127.0.0.1:8765(端口见 <工程>/.cutforge/session) */
  baseUrl: string;
  /** Bearer token(serve 启动时落盘 .cutforge/session;数据面必须持 token) */
  token: string;
  /** 绑定工程根:工具入参缺 root 时自动注入(工作区通道语义;可省) */
  root?: string;
  /** 自定义 fetch 实现(测试注入用;缺省全局 fetch) */
  fetchImpl?: typeof fetch;
}

/**
 * CutForge Editor API 类型化客户端(生成物;册七 T7.1)。
 * 与 /rpc 同一 dispatch 单表(三通道同源,工具集差异恒为 0)。
 */
export class CutforgeClient {
  private readonly baseUrl: string;
  private readonly token: string;
  private readonly root?: string;
  private readonly fetchImpl: typeof fetch;

  constructor(opts: CutforgeOptions) {
    this.baseUrl = opts.baseUrl.replace(/\/$/, "");
    this.token = opts.token;
    this.root = opts.root;
    this.fetchImpl = opts.fetchImpl ?? fetch.bind(globalThis);
  }

  /** 统一工具入口:POST /api/v1/tools/<tool>(转发既有 dispatch 单表)。 */
  async call<T = Record<string, unknown>>(tool: string, args?: ToolArgs): Promise<Envelope<T>> {
    const merged: ToolArgs = { ...(args ?? {}) };
    if (merged["root"] === undefined && this.root !== undefined) {
      merged["root"] = this.root;
    }
    const res = await this.fetchImpl(`${this.baseUrl}/api/v1/tools/${encodeURIComponent(tool)}`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${this.token}` },
      body: JSON.stringify(merged),
    });
    return (await res.json()) as Envelope<T>;
  }

  /** 工具清单(GET /api/v1/tools;schemas/mcp-tools.json 单一真相源)。 */
  async listTools(): Promise<Envelope<{ tools: Array<{ name: string; kind: string; description: string }> }>> {
    const res = await this.fetchImpl(`${this.baseUrl}/api/v1/tools`, {
      headers: { Authorization: `Bearer ${this.token}` },
    });
    return (await res.json()) as Envelope<{ tools: Array<{ name: string; kind: string; description: string }> }>;
  }

  /** 事件流地址(SSE 用 EventSource / 手写解析皆可;token 经查询串)。 */
  eventsUrl(): string {
    return `${this.baseUrl}/api/v1/events?token=${encodeURIComponent(this.token)}`;
  }

  /**
   * 订阅工作区事件(SSE;零依赖手写解析,不依赖 EventSource)。
   * 返回退订函数(AbortController.abort)。`bye` 事件/流结束自动停。
   */
  async subscribeEvents(
    onEvent: (ev: WorkspaceEvent) => void,
    opts: { since?: number; signal?: AbortSignal } = {},
  ): Promise<() => void> {
    const ctrl = new AbortController();
    const onAbort = () => ctrl.abort();
    if (opts.signal) {
      if (opts.signal.aborted) {
        ctrl.abort();
      } else {
        opts.signal.addEventListener("abort", onAbort, { once: true });
      }
    }
    const url = `${this.eventsUrl()}${opts.since !== undefined ? `&since=${opts.since}` : ""}`;
    const res = await fetch(url, {
      headers: { Accept: "text/event-stream", Authorization: `Bearer ${this.token}` },
      signal: ctrl.signal,
    });
    if (!res.ok || !res.body) {
      throw new Error(`SSE 建立失败: HTTP ${res.status}`);
    }
    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buf = "";
    const pump = async (): Promise<void> => {
      for (;;) {
        const { done, value } = await reader.read();
        if (done) {
          return;
        }
        buf += decoder.decode(value, { stream: true });
        let idx: number;
        while ((idx = buf.indexOf("\n\n")) >= 0) {
          const frame = buf.slice(0, idx);
          buf = buf.slice(idx + 2);
          let ev = "message";
          const dataLines: string[] = [];
          for (const line of frame.split("\n")) {
            if (line.startsWith(":")) {
              continue; // 心跳注释
            }
            if (line.startsWith("event:")) {
              ev = line.slice(6).trim();
            } else if (line.startsWith("data:")) {
              dataLines.push(line.slice(5).trim());
            }
          }
          if (!dataLines.length) {
            continue;
          }
          let data: WorkspaceEvent;
          try {
            data = JSON.parse(dataLines.join("\n")) as WorkspaceEvent;
          } catch {
            continue;
          }
          onEvent(data);
          if (ev === "bye") {
            ctrl.abort();
            return;
          }
        }
      }
    };
    pump().catch((err) => {
      if (!ctrl.signal.aborted) {
        throw err;
      }
    });
    return () => {
      ctrl.abort();
      if (opts.signal) {
        opts.signal.removeEventListener("abort", onAbort);
      }
    };
  }

  // ---- 工具方法(78 个;由 schemas/mcp-tools.json 生成) ----

  /** 工程视图(可按轨道/时间窗裁剪)(kind: query) */
  projectGet(args: ProjectGetArgs): Promise<Envelope> {
    return this.call("project_get", args);
  }

  /** 字级时间轴+校准痕迹(唯一时间来源)(kind: query) */
  wordlineGet(args: WordlineGetArgs): Promise<Envelope> {
    return this.call("wordline_get", args);
  }

  /** 粗剪决策+guard 结果(kind: query) */
  cutlistGet(args: CutlistGetArgs): Promise<Envelope> {
    return this.call("cutlist_get", args);
  }

  /** 标注清单(含锚点与状态)(kind: query) */
  notesList(args: NotesListArgs): Promise<Envelope> {
    return this.call("notes_list", args);
  }

  /** CutFlow 阶段状态(_内部状态/S*.json 存在性;0.4.x 旧布局 _state 兼容)(kind: query) */
  stageStatus(args: StageStatusArgs): Promise<Envelope> {
    return this.call("stage_status", args);
  }

  /** OpLog tail(AI 感知用户改动的入口)(kind: query) */
  oplogTail(args: OplogTailArgs): Promise<Envelope> {
    return this.call("oplog_tail", args);
  }

  /** 当前冲突与三方快照引用(kind: query) */
  conflictList(args: ConflictListArgs): Promise<Envelope> {
    return this.call("conflict_list", args);
  }

  /** 成片输出目录(06_成片输出;旧布局 06_output 兼容)产物清单+媒体信息(kind: query) */
  renderProbe(args: RenderProbeArgs): Promise<Envelope> {
    return this.call("render_probe", args);
  }

  /** 后端能力对等矩阵(ADR-0038) */
  capabilityMatrix(): Promise<Envelope> {
    return this.call("capability_matrix");
  }

  /** 改片段属性(同 patch 重复应用结果一致);册四 T4.6 起 patch.fx 承接片段特效(整对象替换:combo 叠加栈上限 3 顺序即应用顺序 + in/out 槽位;目录 GET /catalogs);册五 T5.1 起 patch.keyframes 承接关键帧(整组替换,IR v3;投影 timeline_get 的 keyframeSamples 供壳曲线编辑器,壳零插值)(kind: write) */
  clipUpdate(args: ClipUpdateArgs): Promise<Envelope> {
    return this.call("clip_update", args);
  }

  /** 在时间点切分片段(已切则幂等返回)(kind: write) */
  clipSplit(args: ClipSplitArgs): Promise<Envelope> {
    return this.call("clip_split", args);
  }

  /** 删除片段(kind: write) */
  clipDelete(args: ClipDeleteArgs): Promise<Envelope> {
    return this.call("clip_delete", args);
  }

  /** 应用粗剪决策(RFC7386 merge-patch 到 cutlist.json)(kind: write) */
  cutApply(args: CutApplyArgs): Promise<Envelope> {
    return this.call("cut_apply", args);
  }

  /** 改字幕卡文本(text 轨片段的 text 字段)(kind: write) */
  subtitleSet(args: SubtitleSetArgs): Promise<Envelope> {
    return this.call("subtitle_set", args);
  }

  /** 改字幕卡时间(受卡时间余量规则约束)(kind: write) */
  subtitleRetime(args: SubtitleRetimeArgs): Promise<Envelope> {
    return this.call("subtitle_retime", args);
  }

  /** 新增叠加元素(贴图/卡片/Logo;需 requestId 去重)(kind: write) */
  overlayAdd(args: OverlayAddArgs): Promise<Envelope> {
    return this.call("overlay_add", args);
  }

  /** 加音效落点(密度 ≤2 个/15s;需 requestId 去重)(kind: write) */
  sfxAdd(args: SfxAddArgs): Promise<Envelope> {
    return this.call("sfx_add", args);
  }

  /** 创建标注(AI 反向提问走 author=agent)(kind: write) */
  notesAdd(args: NotesAddArgs): Promise<Envelope> {
    return this.call("notes_add", args);
  }

  /** 结案标注(reply + opIds 回执)(kind: write) */
  notesResolve(args: NotesResolveArgs): Promise<Envelope> {
    return this.call("notes_resolve", args);
  }

  /** 否决标注(kind: write) */
  notesReject(args: NotesRejectArgs): Promise<Envelope> {
    return this.call("notes_reject", args);
  }

  /** 移动片段(改 startMs;可跨同 kind 轨道;同轨重叠 GUARD_FAILED)(kind: write) */
  clipMove(args: ClipMoveArgs): Promise<Envelope> {
    return this.call("clip_move", args);
  }

  /** 复制片段(新 id,放到同轨指定起点;粘贴 = 复制+落点)(kind: write) */
  clipDuplicate(args: ClipDuplicateArgs): Promise<Envelope> {
    return this.call("clip_duplicate", args);
  }

  /** 新增空轨道(kind: video|audio|text,id 确定性生成)(kind: write) */
  trackAdd(args: TrackAddArgs): Promise<Envelope> {
    return this.call("track_add", args);
  }

  /** 撤销(可按 actor 批量撤销 AI 改动)(kind: write) */
  undo(args: UndoArgs): Promise<Envelope> {
    return this.call("undo", args);
  }

  /** 重做(kind: write) */
  redo(args: RedoArgs): Promise<Envelope> {
    return this.call("redo", args);
  }

  /** 调 rs_run.py --only <stage>(kind: orchestrate) */
  stageRun(args: StageRunArgs): Promise<Envelope> {
    return this.call("stage_run", args);
  }

  /** 调对应目录 rebuild.py(kind: orchestrate) */
  stageRebuild(args: StageRebuildArgs): Promise<Envelope> {
    return this.call("stage_rebuild", args);
  }

  /** 调 rs_verify.py 分级自检(kind: orchestrate) */
  verifyRun(args: VerifyRunArgs): Promise<Envelope> {
    return this.call("verify_run", args);
  }

  /** 调 rs_sync.py(对齐断言/音频闸/QC)(kind: orchestrate) */
  syncCheck(args: SyncCheckArgs): Promise<Envelope> {
    return this.call("sync_check", args);
  }

  /** 调 rs_render.py(backend=ffmpeg,默认)或 cutforge-render(backend=cutforge,B6 已接线)(kind: orchestrate) */
  render(args: RenderArgs): Promise<Envelope> {
    return this.call("render", args);
  }

  /** 调 rs_jy_draft.py(前置:剪映未运行)(kind: orchestrate) */
  exportJianying(args: ExportJianyingArgs): Promise<Envelope> {
    return this.call("export_jianying", args);
  }

  /** 时间线投影(逐 clip 全字段:id/track/trackKind/src/startMs/endMs/durationMs/sourceInMs/speed/volume/opacity/scale/position/overlay/motion/text/freezeMs/transition/fade/punchIn/role;endMs 由内核计算,壳禁时间线语义;后四者为 E4-3 只读展示面)(kind: query) */
  timelineGet(args: TimelineGetArgs): Promise<Envelope> {
    return this.call("timeline_get", args);
  }

  /** 媒体元信息(E3-2/B12 probe 接线):durationMs/分辨率/是否含音轨;src 为工程内相对路径;ffprobe 不可用如实 DEP_MISSING(kind: query) */
  mediaProbe(args: MediaProbeArgs): Promise<Envelope> {
    return this.call("media_probe", args);
  }

  /** 素材浏览(E3-3):列工程内可导入媒体(name/path/bytes/kind;前 64 个附 durationMs)。壳素材面板与 Agent 共用;路径校验与 /media 同一 canonicalize 实现(kind: query) */
  mediaBrowse(args: MediaBrowseArgs): Promise<Envelope> {
    return this.call("media_browse", args);
  }

  /** 异步启动 cutforge-render(E5-3):立即返回 runId;进度用 render_progress 轮询;不持 workspace 锁(kind: orchestrate) */
  renderRun(args: RenderRunArgs): Promise<Envelope> {
    return this.call("render_run", args);
  }

  /** 查询 render_run 的进度:state(running/ok/fail)+ 最近 JSON 行进度 + 产物路径(kind: query) */
  renderProgress(args: RenderProgressArgs): Promise<Envelope> {
    return this.call("render_progress", args);
  }

  /** 渲染指定时间点的一帧合成画面(A2/T2.4 精确预览):含转场/叠加/字幕烧录的真实效果;同步返回不持工程锁;缓存键=工作区指纹+atMs(100ms 量化)+画幅+渲染版本,改一笔即 miss;落盘 .cutforge/render-cache/frame/,壳经 /media 以返回的 media 相对路径加载(kind: orchestrate) */
  renderFrame(args: RenderFrameArgs): Promise<Envelope> {
    return this.call("render_frame", args);
  }

  /** 素材导入/新建片段(E3-1):内部走 Command::ClipInsert;durationMs 缺省由 ffprobe 探测自动填(E3-2);src 须为工程内相对路径;非幂等写,需 requestId 去重(kind: write) */
  clipAdd(args: ClipAddArgs): Promise<Envelope> {
    return this.call("clip_add", args);
  }

  /** 新建空工程(B11):最小 IR(canvas/fps/schemaVersion/稳定 id 空轨道);与 CLI `new` 子命令同走 cutforge_io::scaffold;工程已存在拒绝覆盖(kind: write) */
  projectNew(args: ProjectNewArgs): Promise<Envelope> {
    return this.call("project_new", args);
  }

  /** 设置片段转场(clip.transition):type 必给(基础枚举 fade/wipeleft/wipeup/slideleft/circleopen/cut/none;cut/none=显式硬切或关闭);durMs/fx/reason 可选,按字段合并不覆盖未给字段;全量转场目录(ffmpeg xfade 58 项实测)走 fx="tr.<id>"(目录 GET /catalogs),未注册 fxId 渲染端降级 type 并 WARN;枚举外 type 由 schema 层拒绝(SCHEMA_INVALID)(kind: write) */
  transitionSet(args: TransitionSetArgs): Promise<Envelope> {
    return this.call("transition_set", args);
  }

  /** 设置片段入场/出场动效(clip.motion):in/inMs/out/outMs/inFx/outFx 至少给一,按字段合并不覆盖未给字段;册四 T4.6 枚举扩至真实渲染目录(schemas/fx-catalog.json motion.*);inFx/outFx=mo.<id> 直通别名优先于枚举;枚举外值由 schema 层拒绝(SCHEMA_INVALID)(kind: write) */
  motionSet(args: MotionSetArgs): Promise<Envelope> {
    return this.call("motion_set", args);
  }

  /** 设置工程级背景乐(doc.bgm):src 为工程内相对路径(设置/合并;工程尚无 bgm 时必给);src 显式 null=清除背景乐;gainDb/ducking/loop 可选按字段合并,新建时落 schema 默认(gainDb=-18/ducking=true/loop=true)(kind: write) */
  bgmSet(args: BgmSetArgs): Promise<Envelope> {
    return this.call("bgm_set", args);
  }

  /** 片段修剪四模式(册四 T4.2):trim=单边伸缩(edge 必给,startMs/durationMs/sourceInMs 联动);roll=相邻边界双边联动(总时长不变,无贴合邻居 GUARD_FAILED);slip=内容平移(sourceInMs 平移,时间线占位不变,越素材末尾 GUARD_FAILED,需 ffprobe);slide=位置平移(贴合邻居让位/压缩)。硬约束(时长>0/不越 0/无重叠)违反 GUARD_FAILED(kind: write) */
  clipTrim(args: ClipTrimArgs): Promise<Envelope> {
    return this.call("clip_trim", args);
  }

  /** 播放头处所有轨命中的片段一次全分割(单 Op,undo 一刀还原);切点在片段内部才切,无命中幂等回执(kind: write) */
  clipSplitAll(args: ClipSplitAllArgs): Promise<Envelope> {
    return this.call("clip_split_all", args);
  }

  /** 轨道属性 patch(按字段合并,None=不改):name/locked/mute/solo/hidden/heightPx/color;静音/独奏的渲染混音联动候 BE3(字段与命令链本册就位);heightPx 低于 schema 允许集 SCHEMA_INVALID(kind: write) */
  trackUpdate(args: TrackUpdateArgs): Promise<Envelope> {
    return this.call("track_update", args);
  }

  /** 删除指定轨上包含 tMs 的间隙,后继片段整体左移闭合(单 Op 原子);首段前空档亦视作间隙;tMs 位于片段内部或全部片段之后 GUARD_FAILED(kind: write) */
  clipGapDelete(args: ClipGapDeleteArgs): Promise<Envelope> {
    return this.call("clip_gap_delete", args);
  }

  /** 复制片段到服务端会话态剪贴板(不产 Op、不升 rev、不可撤销;重开工作区即清空);配合 clip_paste_at 使用(kind: write) */
  clipCopy(args: ClipCopyArgs): Promise<Envelope> {
    return this.call("clip_copy", args);
  }

  /** 带属性粘贴剪贴板内容到指定轨+时间点(volume/speed/transition 等原样携带,id 在目标轨重分配);跨 kind GUARD_FAILED;落点重叠 GUARD_FAILED;剪贴板为空 PRECONDITION_FAILED;非幂等写,需 requestId 去重(kind: write) */
  clipPasteAt(args: ClipPasteAtArgs): Promise<Envelope> {
    return this.call("clip_paste_at", args);
  }

  /** 新建文本片段到文本轨(册四 T4.7;单 Op;atMs=播放头毫秒由壳传值;text 之后即可 clip_update 再改;渲染经 ADR-0016 生成临时 ASS 烧录,目录 GET /catalogs 的 huazi 模板可挂)(kind: write) */
  textAdd(args: TextAddArgs): Promise<Envelope> {
    return this.call("text_add", args);
  }

  /** SRT/ASS 字幕导入 → 批量文本片段(册四 T4.7;整批单 Op 原子——任一落点重叠整批拒绝;解析/导出同一纯函数层,往返零丢失)(kind: write) */
  subtitleImport(args: SubtitleImportArgs): Promise<Envelope> {
    return this.call("subtitle_import", args);
  }

  /** 文本轨 → SRT/ASS 导出(册四 T4.7;派生物产物,不产 Op 不改 IR;缺省落 06_成片输出/subtitles_<轨>.<格式>;media 相对路径可经 /media 加载)(kind: orchestrate) */
  subtitleExport(args: SubtitleExportArgs): Promise<Envelope> {
    return this.call("subtitle_export", args);
  }

  /** 文本轨批量查找替换(册四 T4.7;单 Op 原子;trackId 缺省 = 全部文本轨;零匹配幂等零 Op)(kind: write) */
  subtitleReplace(args: SubtitleReplaceArgs): Promise<Envelope> {
    return this.call("subtitle_replace", args);
  }

  /** 波形 peaks 生成(册四 T4.8;ffmpeg 解单声道 PCM → 多级分辨率 min/max 桶 JSON,落 .cutforge/peaks-cache/ 内容寻址 = 路径+mtime+size+桶数档,改素材即 miss;时间线波形绘制是 FE 活)(kind: orchestrate) */
  mediaPeaks(args: MediaPeaksArgs): Promise<Envelope> {
    return this.call("media_peaks", args);
  }

  /** 抽帧缩略图(册四 T4.1;ffmpeg 单帧 → PNG 落 .cutforge/thumb-cache/,内容寻址 = 路径+mtime+size+atMs+宽度;atMs 缺省 = 时长 10%)(kind: orchestrate) */
  mediaThumbnail(args: MediaThumbnailArgs): Promise<Envelope> {
    return this.call("media_thumbnail", args);
  }

  /** 1/2 分辨率代理生成/查询(册四 T4.1;.cutforge/proxy/ 内容寻址;渲染端 render/render_frame 的 useProxy 显式 opt-in 消费同一目录——预览走代理,导出走原片)(kind: orchestrate) */
  mediaProxy(args: MediaProxyArgs): Promise<Envelope> {
    return this.call("media_proxy", args);
  }

  /** 节拍检测(册四 T4.8;onset-energy 启发式:RMS 包络 → 半波整流差分 → 自相关 BPM + 相位网格;degraded=true 诚实标注,置信度随产出;纯计算不落盘不产 Op,标记落盘与吸附是 FE 活)(kind: orchestrate) */
  audioBeats(args: AudioBeatsArgs): Promise<Envelope> {
    return this.call("audio_beats", args);
  }

  /** 导入 3D LUT(.cube,册五 T5.2):结构合法性校验(3D 主格式,33³ 格)后拷入 .cutforge/luts/(同名同内容幂等覆盖,同名异内容追加序号);返回相对路径供 clip.grade.lut 引用(段缓存键含 LUT 内容哈希)(kind: orchestrate) */
  lutImport(args: LutImportArgs): Promise<Envelope> {
    return this.call("lut_import", args);
  }

  /** 示波器数据后端(册五 T5.2):帧像素 → 亮度波形列采样 / UV 矢量散点聚合(64×64)/ RGB 直方图(64 桶)三类数据 JSON;缓存 .cutforge/scope-cache/(内容寻址);壳 canvas 绘制是 FE 活,本工具只供数据(kind: orchestrate) */
  scopeData(args: ScopeDataArgs): Promise<Envelope> {
    return this.call("scope_data", args);
  }

  /** 响度计(册五 T5.3):ffmpeg loudnorm 测量成片/段落的 LUFS/TP/LRA/阈值 → JSON(与导出双 pass 同源);可给 target 得 deviation/within1LU(AC-5.3 的 ≤1LU 判定);只读不持锁(kind: query) */
  audioLoudness(args: AudioLoudnessArgs): Promise<Envelope> {
    return this.call("audio_loudness", args);
  }

  /** 硬件编码探测(册五 T5.6):ffmpeg -encoders 清单(nvenc/qsv/amf 编译期在位)+ 试编可用性(驱动/会话真可用);auto 缺省 = libx264 确定性基线,hw 试编失败优雅降级(AC-5.6);只读不持锁(kind: query) */
  encodeProbe(args: EncodeProbeArgs): Promise<Envelope> {
    return this.call("encode_probe", args);
  }

  /** 渲染队列操作(册五 T5.6):list 查询全队列 / pause 暂停(queued/running;运行中=终止子进程转 paused)/ resume 恢复排队 / cancel 取消 / retry 重试(fail/canceled/ok → 重新排队,渲染缓存吸收重跑成本);并发上限 env CUTFORGE_RENDER_CONCURRENCY(缺省 1);状态事件接既有 render.progress 事件面(kind: orchestrate) */
  renderQueue(args: RenderQueueArgs): Promise<Envelope> {
    return this.call("render_queue", args);
  }

  /** 复合片段打包(册五 T5.4/ADR-0019):选中多片段打包为一个复合片段(单 Op 原子;原片段移除,子时间线=选中片段局部时间域)。守卫:≥2 片段/全部视频轨/两两不重叠且首尾相接/不得含复合片段(深度上限两级)。编辑复合内部=解包→改→重打包(kind: write) */
  compoundCreate(args: CompoundCreateArgs): Promise<Envelope> {
    return this.call("compound_create", args);
  }

  /** 复合片段解包(册五 T5.4/ADR-0019):还原为子片段落回所在轨(单 Op 原子;局部时间域平移回主时间线,id 重新确定性分配;打包的逆操作)(kind: write) */
  compoundUnbind(args: CompoundUnbindArgs): Promise<Envelope> {
    return this.call("compound_unbind", args);
  }

  /** 多机位同步分析(册五 T5.4/ADR-0019):同源多角度素材数组 → 音频包络互相关对齐 → 各素材偏移 ms(angles[0]=基准,offset 恒 0;offset 语义=角度源时间轴相对基准的滞后)。engine=envelope-xcorr,degraded=true 启发式诚实标注;纯计算不落盘不产 Op(kind: orchestrate) */
  multicamSync(args: MulticamSyncArgs): Promise<Envelope> {
    return this.call("multicam_sync", args);
  }

  /** 多机位切换序列展开(册五 T5.4/ADR-0019:多机位=序列不是实体):切换点列表 → 展开为普通片段序列落同一条轨(单 Op 原子;sourceInMs 已含同步偏移)。angles[i].offsetMs 接 multicam_sync 输出(kind: write) */
  multicamCut(args: MulticamCutArgs): Promise<Envelope> {
    return this.call("multicam_cut", args);
  }

  /** 场景剪切检测(册五 T5.4):抽帧差分(灰度 64x36 @sampleFps)→ 自适应阈值局部极大 → 剪切点列表(engine=frame-diff,degraded=true 启发式诚实标注);autoSplit.trackId 给定时按切点自动切段(Command::TrackSplitAt 单 Op 原子;切点不在片段内部时 GUARD 拒绝)(kind: write) */
  sceneDetect(args: SceneDetectArgs): Promise<Envelope> {
    return this.call("scene_detect", args);
  }

  /** 互操作导出(册五 T5.5/ADR-0019 手写最小子集):format=otio → OTIO JSON(Timeline/Track(Video/Audio)/Clip(source_range+相对路径)/Gap/Marker/Transition 基础型/Stack(复合↔嵌套 Stack);子集外轨型 WARN 留痕)或 format=edl → EDL CMX3600 文本(视频轨逐事件 C/D,转场映射 D 溶解;生成器与版本写头注释)。派生物产物,不产 Op 不改 IR;缺省落 06_成片输出/<slug>.<ext>(kind: orchestrate) */
  otioExport(args: OtioExportArgs): Promise<Envelope> {
    return this.call("otio_export", args);
  }

  /** OTIO 导入(册五 T5.5/ADR-0019):OTIO JSON → 新工程(从零起步,project_new 同类免锁创建;目标 root 须不存在,拒绝覆盖)。子集外元素(未知轨型/效果栈/时间变形等)WARN 留痕不静默丢;Track kind 仅 Video/Audio,未知转场类型降级 fade 并 WARN(kind: orchestrate) */
  otioImport(args: OtioImportArgs): Promise<Envelope> {
    return this.call("otio_import", args);
  }

  /** 工程布局迁移(册六 T6.1/ADR-0021):V1(0.4.x 英文目录)/V2(中文阶段目录)→ V3 扁平布局(media/ + 真相源在根 + exports/);一次性到位,幂等(v3 工程 = NOOP),映射目标已存在整体拒绝(CONFLICT,盘面不动);目录级搬运,OpLog/rev/notes/.cutforge 随工程根原地不动,完整性零影响(kind: write) */
  migrateLayout(args: MigrateLayoutArgs): Promise<Envelope> {
    return this.call("migrate_layout", args);
  }

  /** 工程库管理(册六 T6.1;T6.4 增 export_cfproj):action=new(新建,scaffold 同源,layout v2/v3)/rename/copy/archive/unarchive/delete/export_cfproj(.cfproj 工程描述快照,serve 关联打开面);root=库根(env CUTFORGE_PROJECTS,缺省 %USERPROFILE%\CutForge\Projects);操作=目录级移动/复制,OpLog 完整性不动;活进程持锁的工程拒绝移动;delete 移入 .trash/(可捞回)(kind: write) */
  libraryManage(args: LibraryManageArgs): Promise<Envelope> {
    return this.call("library_manage", args);
  }

  /** 工程库清单(册六 T6.1):卡片元数据从 project.json 轻量派生(slug/fps/画幅/时长=IR 投影 max endMs/rev/修改时间/缩略图=.cutforge/thumb-cache 最新产物);不逐工程 ffprobe(列表成本可控);query 子串过滤 name/slug(大小写不敏感);includeArchived 并入 .archives 归档区;坏工程如实标 valid=false(kind: query) */
  libraryList(args: LibraryListArgs): Promise<Envelope> {
    return this.call("library_list", args);
  }

  /** 崩溃恢复(册六 T6.1/AC-6.1):action=list 列库内可恢复工程(.cutforge/lock 在盘且 pid 已死/锁龄超阈;附会话摘要证据 revFrom/revTo);action=recover+name 对指定工程执行恢复(清残留锁 + OpLog 一致性校验:半行截断/rev 对账/规范形落盘,复用 Workspace::open_for_write 既有语义)(kind: write) */
  libraryRecover(args: LibraryRecoverArgs): Promise<Envelope> {
    return this.call("library_recover", args);
  }

  /** 导出前检查清单(册六 T6.3;轻探测不渲全片):缺失素材/黑帧风险(首末帧亮度,源域抽帧)/静音段(声轨覆盖间隙+逐段源 RMS 启发式)/时长(窗口裁剪后)/响度预估(audio_loudness 复用:最新成片在位则实测,否则 null);启发式面如实打 heuristic 标注;只读不持锁(kind: query) */
  exportPreflight(args: ExportPreflightArgs): Promise<Envelope> {
    return this.call("export_preflight", args);
  }

  /** 多画幅批量导出(册六 T6.3):action=run(缺省)一次排队 outputs 全变体任务(ratios 缺省取工程 outputs,再缺省 9x16/16x9/1x1;逐变体 runId 走渲染队列,进度/取消/重试复用 render_queue);action=status 按 parentRunId 聚合子任务状态(ok/fail/running)(kind: orchestrate) */
  exportAllVariants(args: ExportAllVariantsArgs): Promise<Envelope> {
    return this.call("export_all_variants", args);
  }

  /** 素材拷贝导入(册六 T6.2;FE1 拷贝导入通道欠账收口):src=绝对路径或素材库相对引用(libraryRoot 缺省 CUTFORGE_MEDIA/默认根),拷入工程布局感知落点(v3=media/,v2=01_原始素材/,v1=01_materials/);同名同内容幂等覆盖、异内容追加序号;tmp+rename 原子落盘;不产 Op 不改 IR(返回 src 可直接喂 clip_add/bgm_set)(kind: write) */
  mediaImport(args: MediaImportArgs): Promise<Envelope> {
    return this.call("media_import", args);
  }

  /** 本地素材库 manifest(册六 T6.2;库根 library.json:类型/标签/时长/引用):action=list(缺省)扫描合并(在位文件↔条目按引用对齐,标签持久,派生索引幂等落盘)+ kind/tag/query 过滤;action=tag 改条目标签(entry+tags);root=素材库根(env CUTFORGE_MEDIA 缺省面同源);只读工程不持锁(kind: query) */
  mediaLibrary(args: MediaLibraryArgs): Promise<Envelope> {
    return this.call("media_library", args);
  }

  /** 工程打包为 .cfpkg 单文件容器(册七 T7.6):manifest + project 真相源(v3 契约名)+ oplog + media 引用素材(includeMedia 缺省 true;引用在、文件缺记 missing 不阻断)+ 可选 exports(includeExports 缺省 false);out 缺省 <root>/<slug>.cfpkg;解包走 project_unpackage;容器语义见 docs/PROJECT-FORMAT.md(kind: write) */
  projectPackage(args: ProjectPackageArgs): Promise<Envelope> {
    return this.call("project_package", args);
  }

  /** 解包 .cfpkg 到新工程目录(册七 T7.6):真相源落 v3 契约位、素材原位还原(src 相对路径零改写)、OpLog 随包恢复(撤销链保留);root = 新工程目录(必须不存在或为空,拒绝覆盖);清单校验 format/formatVersion/project 真相源,条目名防 zip-slip(穿越/绝对路径/反斜杠拒绝)(kind: write) */
  projectUnpackage(args: ProjectUnpackageArgs): Promise<Envelope> {
    return this.call("project_unpackage", args);
  }

}
