// ARL-CORE · CutForge 权利人核心文件(许可见 LICENSE 1.3;清单见 CORE-FILES)
//! 文本片段 → 临时 ASS 的确定性生成(册四 A4 T4.7;ADR-0016 主路线)。
//!
//! **纯函数纪律**:同输入两次生成 byte 相同(无时钟、无随机、无环境读取;
//! 迭代序 = 工程轨道/片段数组序;浮点统一走 steps::fmt_f64 去尾零)。
//! 单测直接对拍生成产物(确定性测试 + 语义测试)。
//!
//! 生成物不进盘面、不进 OpLog(渲染临时件,ADR-0013 精神:渲染侧派生物不持真相),
//! 由 lib::render 合成后写入渲染缓存 tmp、走与字幕烧录完全相同的 subtitles 滤镜通道。
//!
//! 样式映射:textStyle 字段 → 逐片段 Style 行(片段级样式,不共享——样式跟随片段
//! 而非轨道,检查器改一片段不影响邻段);花字模板(catalog::huazi_list)产出
//! override 标签;卡拉OK = 片段时长逐字均分 \kf;位置 x,y(画布像素)→ \pos。

use crate::catalog;
use crate::steps::fmt_f64;
use cutforge_core::model::{Clip, Project, Track, TrackKind};
use cutforge_core::text_style::{TextStyle, color_to_ass};

/// ASS 默认样式参数(与 text_style.rs 的"缺省由渲染端裁决"对齐)。
const DEFAULT_FONT: &str = "sans-serif";
const DEFAULT_FONT_SIZE: f64 = 64.0;
const DEFAULT_COLOR: &str = "#FFFFFF";
const DEFAULT_OUTLINE_COLOR: &str = "#000000";
const DEFAULT_OUTLINE_WIDTH: f64 = 2.0;
const DEFAULT_BORDER_STYLE: u8 = 1;
const DEFAULT_BACK_COLOR: &str = "#000000";
const DEFAULT_SHADOW: f64 = 0.0;
const DEFAULT_OPACITY: f64 = 1.0;
const DEFAULT_LINE_SPACING: f64 = 0.0;
/// 无 x,y 时的水平边距(PlayRes 像素)与垂直边距(画布高的 10%)。
const MARGIN_LR: u64 = 40;
const MARGIN_V_PERMILLE: u64 = 100;

/// 文本渲染路径的结构化 WARN(渲染端降级留痕;exec_subtitle 并入进度事件)。
pub fn generation_warnings(project: &Project) -> Vec<String> {
    let mut out = Vec::new();
    for t in text_tracks(project) {
        for c in &t.clips {
            let Some(text) = &c.text else { continue };
            if text.trim().is_empty() {
                continue;
            }
            if let Some(hz) = &c.huazi
                && catalog::find_huazi(&hz.template).is_none()
            {
                out.push(format!(
                    "clip {} 花字({}) 未注册,降级纯文本;",
                    c.id, hz.template
                ));
            }
        }
    }
    out
}

/// 文本轨视图(kind=Text 且未被 mute/hidden 静默的轨;册四 BE3b:文本轨无音频,
/// mute 语义落地为"文本静默",与 hidden 同效——定义见 schema track.mute 注记)。
/// 册五 T5.4:调整层(kind=Adjust)上的文本片段同通道纳入——调整层语义 =
/// 作用于下方全部轨的顶层叠加,与文本轨烧录通道完全同源。
pub fn text_tracks(project: &Project) -> Vec<&Track> {
    project
        .tracks
        .iter()
        .filter(|t| t.kind == TrackKind::Text || t.kind == TrackKind::Adjust)
        .filter(|t| !(t.mute.unwrap_or(false) || t.hidden.unwrap_or(false)))
        .collect()
}

/// 工程是否含可见文本片段(渲染端是否需要生成文本 ASS 的判定)。
pub fn has_visible_text(project: &Project) -> bool {
    text_tracks(project).iter().any(|t| {
        t.clips
            .iter()
            .any(|c| c.text.as_deref().is_some_and(|s| !s.trim().is_empty()))
    })
}

/// 工程文本轨 → 完整 ASS 文档(纯函数;无可文本片段 → None)。
/// PlayRes = 画布(样式像素坐标与画布一一对应)。
pub fn generate(project: &Project) -> Option<String> {
    if !has_visible_text(project) {
        return None;
    }
    let (w, h) = (project.canvas.width, project.canvas.height);
    let mut styles = String::new();
    let mut events = String::new();
    for t in text_tracks(project) {
        for c in &t.clips {
            let Some(text) = &c.text else { continue };
            if text.trim().is_empty() {
                continue;
            }
            let style_name = style_name(&c.id);
            styles.push_str(&style_line(&style_name, c, w, h));
            events.push_str(&dialogue_line(&style_name, c, text));
        }
    }
    Some(format!(
        "[Script Info]\n; generated by cutforge-render (deterministic text ASS, ADR-0016)\nScriptType: v4.00+\nPlayResX: {w}\nPlayResY: {h}\nWrapStyle: 2\nScaledBorderAndShadow: yes\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n{styles}\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n{events}"
    ))
}

/// 片段 id → ASS 样式名(CF_ 前缀 + 片段 id;片段 id 全工程唯一,样式名不撞
/// 外部字幕的 Style;id 字符集为安全子集,无需转义)。
fn style_name(clip_id: &str) -> String {
    format!("CF_{clip_id}")
}

/// 逐片段 Style 行(textStyle 全字段消费;花字模板的样式级覆写在此并——
/// BorderStyle/底衬等 override 无法表达的维度由 Style 行承载)。
fn style_line(name: &str, c: &Clip, _w: u32, h: u32) -> String {
    let ts: TextStyle = c.text_style.clone().unwrap_or_default();
    let mut hz_style = serde_json::Map::new();
    if let Some(hz) = &c.huazi
        && let Some(def) = catalog::find_huazi(&hz.template)
    {
        for (k, v) in &def.style {
            hz_style.insert(k.clone(), v.clone());
        }
    }
    let hz_get = |key: &str| hz_style.get(key).and_then(|v| v.as_str()).map(String::from);
    let font = ts
        .font_family
        .clone()
        .or_else(|| c.font.as_ref().map(|f| f.family.clone()))
        .unwrap_or_else(|| DEFAULT_FONT.into());
    let size = ts.font_size.unwrap_or(DEFAULT_FONT_SIZE);
    let opacity = ts.opacity.unwrap_or(DEFAULT_OPACITY).clamp(0.0, 1.0);
    // 不透明度 → ASS alpha(00=不透明,FF=全透);作用于主色/描边/底衬三处
    let alpha = format!("{:02X}", ((1.0 - opacity) * 255.0).round() as u8);
    let primary_raw = hz_get("primaryColor").unwrap_or_else(|| {
        color_to_ass(ts.color.as_deref().unwrap_or(DEFAULT_COLOR), DEFAULT_COLOR)
    });
    let primary = with_alpha(&primary_raw, &alpha);
    let outline_raw = hz_get("outlineColor").unwrap_or_else(|| {
        color_to_ass(
            ts.outline_color.as_deref().unwrap_or(DEFAULT_OUTLINE_COLOR),
            DEFAULT_OUTLINE_COLOR,
        )
    });
    let outline_color = with_alpha(&outline_raw, &alpha);
    let back_raw = hz_get("backColor").unwrap_or_else(|| {
        color_to_ass(
            ts.back_color.as_deref().unwrap_or(DEFAULT_BACK_COLOR),
            DEFAULT_BACK_COLOR,
        )
    });
    let back = with_alpha(&back_raw, &alpha);
    let border_style = hz_style
        .get("borderStyle")
        .and_then(|v| v.as_u64())
        .map(|v| v as u8)
        .or(ts.border_style)
        .unwrap_or(DEFAULT_BORDER_STYLE);
    let outline_w = hz_style
        .get("outlineWidth")
        .and_then(|v| v.as_f64())
        .or(ts.outline_width)
        .unwrap_or(DEFAULT_OUTLINE_WIDTH)
        .clamp(0.0, 20.0);
    let shadow = ts.shadow.unwrap_or(DEFAULT_SHADOW).clamp(0.0, 20.0);
    let align = ts.align_num();
    let secondary = "&H00FFFFFF"; // 卡拉OK未唱色(仅 karaoke 消费;非卡拉OK不可见维度)
    let no_pos = ts.x.is_none() && ts.y.is_none();
    format!(
        "Style: {name},{font},{size},{primary},{secondary},{outline_color},{back},0,0,0,0,100,100,{spacing},0,{border_style},{outline_w},{shadow},{align},{margin_lr},{margin_lr},{margin_v},1\n",
        spacing = fmt_f64(ts.line_spacing.unwrap_or(DEFAULT_LINE_SPACING)),
        margin_lr = MARGIN_LR,
        margin_v = margin_v(no_pos, align, h),
    )
}

/// 主色/描边/底衬的 alpha 归一:ASS 色串(&HAABBGGRR 或 &HBBGGRR)统一为
/// `&H{alpha}BBGGRR`(无尾 &;确定性形态)。
fn with_alpha(ass_color: &str, alpha: &str) -> String {
    let hex = ass_color.trim_start_matches("&H").trim_end_matches('&');
    if hex.len() == 8 {
        format!("&H{alpha}{}", &hex[2..])
    } else {
        format!("&H{alpha}{hex}")
    }
}

/// 无 x,y 时的垂直边距(底部/顶部对齐 = 画布高 10%,居中 0;
/// 有 \pos 时恒 0——\pos 下边距语义已被锚点取代,不得叠加)。
fn margin_v(no_pos: bool, align: u8, h: u32) -> u64 {
    if !no_pos {
        return 0;
    }
    match align {
        4..=6 => 0,
        _ => h as u64 * MARGIN_V_PERMILLE / 1000,
    }
}

/// 逐片段 Dialogue 行(时窗 = 片段 startMs..startMs+durationMs,时间线绝对;
/// body = 位置/花字/卡拉OK override + 转义正文)。
fn dialogue_line(style_name: &str, c: &Clip, text: &str) -> String {
    let start = ass_time(c.start_ms);
    let end = ass_time(c.start_ms + c.duration_ms);
    let body = body_of(c, text);
    format!("Dialogue: 0,{start},{end},{style_name},,0,0,0,,{body}\n")
}

/// 正文装配:位置 \pos → 花字 override/逐字动画 → 卡拉OK \kf → 转义文本。
fn body_of(c: &Clip, text: &str) -> String {
    let ts: TextStyle = c.text_style.clone().unwrap_or_default();
    let mut prefix = String::new();
    // 位置:x/y 任一给出即走 \pos(像素,PlayRes=画布);锚点 = align。
    if ts.x.is_some() || ts.y.is_some() {
        let x = ts.x.unwrap_or(0.0);
        let y = ts.y.unwrap_or(0.0);
        prefix.push_str(&format!("\\pos({},{})", fmt_f64(x), fmt_f64(y)));
    }
    let escaped = escape_text(text);
    let pre = if prefix.is_empty() {
        String::new()
    } else {
        format!("{{{prefix}}}")
    };
    // 卡拉OK(textStyle.karaoke 或 hz.karaoke 模板):逐字均分 \kf;
    // 已唱/未唱色由 Style 行 primary/secondary 承载(模板 style.primaryColor 覆写)。
    let karaoke = ts.karaoke.unwrap_or(false)
        || c.huazi
            .as_ref()
            .is_some_and(|h| catalog::find_huazi(&h.template).is_some_and(|d| d.karaoke));
    if karaoke {
        return format!("{pre}{}", karaoke_body(text, c.duration_ms));
    }
    // 花字(catalog 模板):参数代入 body / 逐字动画生成器
    if let Some(hz) = &c.huazi
        && let Some(def) = catalog::find_huazi(&hz.template)
    {
        let mut vals: Vec<(&str, String)> = Vec::new();
        for p in &def.params {
            let (v, _) = catalog::huazi_param_value(hz.params.as_ref(), p);
            vals.push((p.name.as_str(), v));
        }
        vals.push(("DUR", c.duration_ms.to_string()));
        let substitute = |tpl: &str| -> String {
            let mut s = tpl.to_string();
            for (k, v) in &vals {
                s = s.replace(&format!("{{{k}}}"), v);
            }
            s
        };
        if let Some(kind) = &def.body_kind {
            let pval = |name: &str, fallback: f64| -> f64 {
                def.params
                    .iter()
                    .find(|p| p.name == name)
                    .map(|p| {
                        catalog::huazi_param_value(hz.params.as_ref(), p)
                            .0
                            .parse::<f64>()
                            .unwrap_or(fallback)
                    })
                    .unwrap_or(fallback)
            };
            let step = pval("stepMs", 70.0);
            return format!("{pre}{}", perchar_body(kind, text, step, pval));
        }
        if let Some(tpl) = &def.body {
            return format!("{pre}{}", substitute(tpl).replace("{TEXT}", &escaped));
        }
    }
    format!("{pre}{escaped}")
}

/// 卡拉OK正文:逐字均分片段时长,\kf(平滑填充,centisecond;尾字吸收取整余数)。
fn karaoke_body(text: &str, duration_ms: u64) -> String {
    let chars: Vec<char> = text.chars().collect();
    let n = chars.len().max(1) as u64;
    let total_cs = duration_ms / 10;
    let per = total_cs / n;
    let mut out = String::new();
    for (i, ch) in chars.iter().enumerate() {
        let k = if i as u64 + 1 == n {
            total_cs - per * (n - 1)
        } else {
            per
        };
        out.push_str(&format!("{{\\kf{k}}}"));
        out.push(*ch);
    }
    out
}

/// 逐字动画正文(吸收旧版 rs_subtitle huazi_body 的三套算法;幅度确定性):
/// - perchar-pop:逐字从 20% 弹出过冲(overshoot)后回落 100%(初始值内联 + 两段 \t);
/// - perchar-typewriter:逐字 alpha FF→00(渐入,打字机);
/// - perchar-wave:逐字相位错开 \fscy 100→100+amp→100(纵向波浪)。
///
/// pval(name, fallback) = 取参数(clip 覆写 → 目录默认,已钳制)。
fn perchar_body(kind: &str, text: &str, step_ms: f64, pval: impl Fn(&str, f64) -> f64) -> String {
    let chars: Vec<char> = text.chars().collect();
    let mut out = String::new();
    for (i, ch) in chars.iter().enumerate() {
        let t0 = (step_ms * i as f64).round() as i64;
        match kind {
            "perchar-pop" => {
                let o100 = (pval("overshoot", 1.1).clamp(1.0, 1.3) * 100.0).round() as i64;
                out.push_str(&format!(
                    "{{\\fscx20\\fscy20\\t({t0},{t1},\\fscx{o100}\\fscy{o100})\\t({t1},{t2},\\fscx100\\fscy100)}}{ch}",
                    t1 = t0 + 120,
                    t2 = t0 + 200,
                ));
            }
            "perchar-typewriter" => {
                out.push_str(&format!(
                    "{{\\alpha&HFF&\\t({t0},{t1},\\alpha&H00&)}}{ch}",
                    t1 = t0 + 120,
                ));
            }
            "perchar-wave" => {
                let up = (100.0 + pval("amp", 15.0).clamp(5.0, 40.0)).round() as i64;
                out.push_str(&format!(
                    "{{\\t({t0},{t1},\\fscy{up})\\t({t1},{t2},\\fscy100)}}{ch}",
                    t1 = t0 + 90,
                    t2 = t0 + 180,
                ));
            }
            _ => out.push(*ch),
        }
    }
    out
}

/// 渲染层转义(IR 文本不变;仅 ASS 呈现层):换行 → \N,花括号 → 全角
/// (防止用户文本被 libass 当 override 标签解析)。
pub fn escape_text(text: &str) -> String {
    text.replace('\r', "")
        .replace('\n', "\\N")
        .replace('{', "｛")
        .replace('}', "｝")
}

/// ms → ASS H:MM:SS.CC(厘秒四舍五入;确定性与溢出安全)。
pub fn ass_time(ms: u64) -> String {
    let cs = (ms + 5) / 10;
    let (s, cc) = (cs / 100, cs % 100);
    format!("{}:{:02}:{:02}.{:02}", s / 3600, s % 3600 / 60, s % 60, cc)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn project(v: serde_json::Value) -> Project {
        serde_json::from_value(v).unwrap()
    }

    fn base(tracks: serde_json::Value) -> serde_json::Value {
        json!({
            "version": 1, "schemaVersion": "2.0.0", "slug": "t", "fps": 30,
            "canvas": {"width": 1080, "height": 1920},
            "tracks": tracks
        })
    }

    fn text_track() -> serde_json::Value {
        json!([{"id": "T1", "kind": "text", "clips": [
            {"id": "T1-001", "startMs": 500, "durationMs": 2000, "text": "你好世界"}
        ]}])
    }

    /// 确定性红线(任务验收):同输入两次生成 byte 相同(含序列化往返后再生成)。
    #[test]
    fn generation_is_byte_deterministic() {
        let p = project(base(text_track()));
        let a = generate(&p).unwrap();
        let b = generate(&p).unwrap();
        assert_eq!(a, b, "同输入两次生成必须 byte 相同");
        let round: Project = serde_json::from_value(serde_json::to_value(&p).unwrap()).unwrap();
        assert_eq!(
            a,
            generate(&round).unwrap(),
            "序列化往返后再生成仍 byte 相同"
        );
    }

    #[test]
    fn none_when_no_visible_text() {
        // 无文本轨
        let p = project(base(json!([{"id": "V1", "kind": "video", "clips": []}])));
        assert!(generate(&p).is_none());
        // 文本轨但 clip 无 text(结构性锚点)
        let p = project(base(json!([{"id": "T1", "kind": "text", "clips": [
            {"id": "T1-001", "startMs": 0, "durationMs": 1000}
        ]}])));
        assert!(generate(&p).is_none());
        // text 为空白串
        let p = project(base(json!([{"id": "T1", "kind": "text", "clips": [
            {"id": "T1-001", "startMs": 0, "durationMs": 1000, "text": "  "}
        ]}])));
        assert!(generate(&p).is_none());
    }

    /// mute/hidden 联动(册四 BE3b):文本轨 mute/hidden 任一 → 不进 ASS。
    #[test]
    fn muted_or_hidden_text_track_is_silent() {
        let mk = |flag: &str| {
            let mut t = json!({"id": "T1", "kind": "text", "clips": [
                {"id": "T1-001", "startMs": 0, "durationMs": 1000, "text": "x"}
            ]});
            t[flag] = json!(true);
            project(base(json!([t])))
        };
        assert!(generate(&mk("mute")).is_none(), "文本轨 mute = 文本静默");
        assert!(generate(&mk("hidden")).is_none(), "文本轨 hidden = 不渲染");
        assert!(!has_visible_text(&mk("mute")));
    }

    /// 全字段样式映射:Style 行逐字段对拍(含颜色 BGR 转换与不透明度 alpha)。
    #[test]
    fn style_line_maps_all_fields() {
        let p = project(base(json!([{"id": "T1", "kind": "text", "clips": [
            {"id": "T1-001", "startMs": 0, "durationMs": 1000, "text": "字",
             "textStyle": {"fontFamily": "黑体", "fontSize": 88, "color": "#FF8800",
                            "outlineColor": "#111111", "outlineWidth": 4, "borderStyle": 1,
                            "backColor": "#222222", "shadow": 3, "align": "topRight",
                            "lineSpacing": 12, "opacity": 0.5, "x": 960, "y": 200}}
        ]}])));
        let ass = generate(&p).unwrap();
        assert!(ass.contains("PlayResX: 1080\nPlayResY: 1920"), "{ass}");
        // 主色 #FF8800 → BBGGRR=0088FF;alpha 0.5 → 80 → &H800088FF
        assert!(
            ass.contains("Style: CF_T1-001,黑体,88,&H800088FF,"),
            "{ass}"
        );
        // 描边色 #111111 → &H80111111;底衬 #222222 → &H80222222
        assert!(ass.contains(",&H80111111,&H80222222,"), "{ass}");
        // BorderStyle 1 / Outline 4 / Shadow 3 / Alignment 9(topRight);有 \pos → MarginV=0
        assert!(ass.contains(",1,4,3,9,40,40,0,1\n"), "{ass}");
        assert!(ass.contains("\\pos(960,200)"), "{ass}");
        let line = ass.lines().find(|l| l.starts_with("Dialogue")).unwrap();
        assert!(
            line.starts_with("Dialogue: 0,0:00:00.00,0:00:01.00,CF_T1-001,,0,0,0,,"),
            "{line}"
        );
    }

    /// 缺省样式:无 textStyle 的旧文本片段照常出字(默认 64px 白字黑描边,
    /// bottomCenter + 10% MarginV)——文本渲染落地不破坏既有工程语义。
    #[test]
    fn default_style_for_legacy_text_clips() {
        let p = project(base(text_track()));
        let ass = generate(&p).unwrap();
        assert!(ass.contains("Style: CF_T1-001,sans-serif,64,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,2,40,40,192,1"), "{ass}");
        // 时窗:startMs=500 → 0:00:00.50,end=2500 → 0:00:02.50
        assert!(
            ass.contains("Dialogue: 0,0:00:00.50,0:00:02.50,CF_T1-001,,0,0,0,,你好世界"),
            "{ass}"
        );
    }

    /// 位置缺省走边距网格:无 x,y 不产 \pos,top 对齐 MarginV=10% 画布高。
    #[test]
    fn margin_grid_when_no_position() {
        let p = project(base(json!([{"id": "T1", "kind": "text", "clips": [
            {"id": "T1-001", "startMs": 0, "durationMs": 1000, "text": "字",
             "textStyle": {"align": "topCenter"}}
        ]}])));
        let ass = generate(&p).unwrap();
        assert!(!ass.contains("\\pos"), "无 x,y 不得产 \\pos");
        assert!(
            ass.contains(",8,40,40,192,1"),
            "top 对齐(topCenter=8)MarginV=192: {ass}"
        );
    }

    /// 卡拉OK:逐字均分 \kf(4 字 2000ms → 每字 50cs;尾字吸收取整余数)。
    #[test]
    fn karaoke_generates_kf_per_char() {
        let p = project(base(json!([{"id": "T1", "kind": "text", "clips": [
            {"id": "T1-001", "startMs": 0, "durationMs": 2000, "text": "四字测试",
             "textStyle": {"karaoke": true}}
        ]}])));
        let ass = generate(&p).unwrap();
        for k in ["\\kf50}四", "\\kf50}字", "\\kf50}测", "\\kf50}试"] {
            assert!(ass.contains(k), "缺 {k}: {ass}");
        }
        // 时长不能整除:3 字 1000ms → 33/33/34(尾字吸收)
        let p = project(base(json!([{"id": "T1", "kind": "text", "clips": [
            {"id": "T1-001", "startMs": 0, "durationMs": 1000, "text": "三字完",
             "textStyle": {"karaoke": true}}
        ]}])));
        let ass = generate(&p).unwrap();
        assert!(
            ass.contains("\\kf33}三") && ass.contains("\\kf33}字") && ass.contains("\\kf34}完"),
            "{ass}"
        );
    }

    /// 花字:模板参数代入 + 样式级覆写 + 未注册降级 WARN。
    #[test]
    fn huazi_template_applies_body_and_style() {
        let p = project(base(json!([{"id": "T1", "kind": "text", "clips": [
            {"id": "T1-001", "startMs": 0, "durationMs": 1500, "text": "标题",
             "huazi": {"template": "hz.outline", "params": {"outline": 8}}}
        ]}])));
        let ass = generate(&p).unwrap();
        assert!(ass.contains("{\\bord8\\3c&H00000000}标题"), "{ass}");
        // DUR 代入(渐变模板)
        let p = project(base(json!([{"id": "T1", "kind": "text", "clips": [
            {"id": "T1-001", "startMs": 0, "durationMs": 1500, "text": "渐",
             "huazi": {"template": "hz.gradient"}}
        ]}])));
        let ass = generate(&p).unwrap();
        assert!(
            ass.contains("{\\1c&H00FFE0\\t(0,1500,\\1c&H20A0FF)}渐"),
            "{ass}"
        );
        // box 模板样式级覆写:borderStyle=3 + outline 10
        let p = project(base(json!([{"id": "T1", "kind": "text", "clips": [
            {"id": "T1-001", "startMs": 0, "durationMs": 1000, "text": "块",
             "huazi": {"template": "hz.box"}}
        ]}])));
        let ass = generate(&p).unwrap();
        assert!(
            ass.contains(",3,10,0,"),
            "BorderStyle=3 + outline 10: {ass}"
        );
        // 未注册模板:降级纯文本 + WARN
        let p = project(base(json!([{"id": "T1", "kind": "text", "clips": [
            {"id": "T1-001", "startMs": 0, "durationMs": 1000, "text": "字",
             "huazi": {"template": "hz.不存在"}}
        ]}])));
        let ass = generate(&p).unwrap();
        assert!(ass.contains(",,字"), "未注册花字降级纯文本: {ass}");
        assert!(!ass.contains("hz."), "{ass}");
        let warns = generation_warnings(&p);
        assert!(
            warns
                .iter()
                .any(|w| w.contains("未注册") && w.contains("hz.不存在")),
            "{warns:?}"
        );
    }

    /// 逐字动画:pop/typewriter/wave 三种 bodyKind 确定性生成(相位步进可见)。
    #[test]
    fn perchar_animation_kinds_generate_deterministically() {
        for tpl in ["hz.pop", "hz.typewriter", "hz.wave"] {
            let p = project(base(json!([{"id": "T1", "kind": "text", "clips": [
                {"id": "T1-001", "startMs": 0, "durationMs": 1000, "text": "AB",
                 "huazi": {"template": tpl}}
            ]}])));
            let a = generate(&p).unwrap();
            let b = generate(&p).unwrap();
            assert_eq!(a, b, "{tpl} 逐字动画必须确定性");
            assert!(a.contains("\\t("), "{tpl} 必须含时序动画标签: {a}");
        }
        // pop 逐字过冲:首字 20%→110→100,第二字相位 +70ms
        let p = project(base(json!([{"id": "T1", "kind": "text", "clips": [
            {"id": "T1-001", "startMs": 0, "durationMs": 1000, "text": "AB",
             "huazi": {"template": "hz.pop"}}
        ]}])));
        let ass = generate(&p).unwrap();
        assert!(ass.contains("\\fscx20\\fscy20\\t(0,120,\\fscx110"), "{ass}");
        assert!(
            ass.contains("\\t(70,190,\\fscx110\\fscy110)"),
            "第二字相位 +70ms: {ass}"
        );
        // typewriter 逐字渐入
        let p = project(base(json!([{"id": "T1", "kind": "text", "clips": [
            {"id": "T1-001", "startMs": 0, "durationMs": 1000, "text": "AB",
             "huazi": {"template": "hz.typewriter"}}
        ]}])));
        let ass = generate(&p).unwrap();
        assert!(
            ass.contains("\\alpha&HFF&\\t(0,120,\\alpha&H00&)}A"),
            "{ass}"
        );
    }

    /// 转义:换行 → \N;花括号 → 全角(IR 文本不变,仅呈现层)。
    #[test]
    fn escaping_newlines_and_braces() {
        assert_eq!(escape_text("a\nb"), "a\\Nb");
        assert_eq!(escape_text("a{\\b1}b"), "a｛\\b1｝b");
        assert_eq!(escape_text("x\r\ny"), "x\\Ny");
        let p = project(base(json!([{"id": "T1", "kind": "text", "clips": [
            {"id": "T1-001", "startMs": 0, "durationMs": 1000, "text": "上\n下"}
        ]}])));
        let ass = generate(&p).unwrap();
        assert!(ass.contains("上\\N下"), "{ass}");
    }

    #[test]
    fn ass_time_formatting() {
        assert_eq!(ass_time(0), "0:00:00.00");
        assert_eq!(ass_time(500), "0:00:00.50");
        assert_eq!(ass_time(61_230), "0:01:01.23");
        assert_eq!(ass_time(3_723_456), "1:02:03.46", "四舍五入 456ms→46cs");
        assert_eq!(ass_time(3_600_000), "1:00:00.00");
    }

    /// 花字 clip 与 textStyle 组合:模板样式覆写主色,用户字号保留。
    #[test]
    fn huazi_combines_with_user_text_style() {
        let p = project(base(json!([{"id": "T1", "kind": "text", "clips": [
            {"id": "T1-001", "startMs": 0, "durationMs": 1000, "text": "合",
             "textStyle": {"fontSize": 100, "color": "#FF0000"},
             "huazi": {"template": "hz.karaoke"}}
        ]}])));
        let ass = generate(&p).unwrap();
        // 卡拉OK模板 primaryColor 覆写样式主色(&H0040FF→&H000040FF);字号仍用用户 100
        assert!(
            ass.contains("Style: CF_T1-001,sans-serif,100,&H000040FF,"),
            "{ass}"
        );
        assert!(ass.contains("{\\kf100}合"), "卡拉OK \\kf 生成: {ass}");
    }
}
