#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""常量单源生成器(计划书 3.9,ADR-0034)。

从 CutFlow 侧唯一真相源生成 schemas/constants.ratios.json,供 Rust 侧
(cutforge-schema,include_str! + 编译期解析)引用;生成物不得手工编辑。

    python tools/gen_constants.py [--check] [--json]

生成期断言:RATIOS 逐键来自 rs_common.RATIOS(直接 import,不做文本解析);
platforms.json 全量进入生成物;fps/canvas 允许集取自 project.schema.json(v1)。
--check 与既有生成物逐键比对,不等则退出码 2(门禁失败)。

退出码:0 通过 / 2 常量漂移 / 3 前置缺失 / 4 内部错误。
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CUTFLOW_REPO = Path(os.environ.get("CUTFLOW_REPO", r"E:\平日资料\GitHub\CutFlow"))
OUT_PATH = REPO_ROOT / "schemas" / "constants.ratios.json"


def _emit(ok: bool, code: str, message: str, data: dict, as_json: bool) -> int:
    envelope = {"ok": ok, "code": code, "message": message, "data": data}
    if as_json:
        print(json.dumps(envelope, ensure_ascii=False, indent=2))
    else:
        print(f"[{'PASS' if ok else 'FAIL'}] {code}: {message}")
    return {"OK": 0, "CONST_DRIFT": 2, "NO_ENV": 3, "INTERNAL": 4}.get(code, 4)


def build_constants() -> dict:
    scripts_dir = CUTFLOW_REPO / "skills" / "cutflow" / "scripts"
    if not (CUTFLOW_REPO / ".git").exists():
        raise FileNotFoundError(f"CutFlow 仓库不存在: {CUTFLOW_REPO}(设 CUTFLOW_REPO 覆盖)")
    sys.path.insert(0, str(scripts_dir))
    try:
        import rs_common  # noqa: PLC0415 — 生成期唯一合法的 import 点
    finally:
        sys.path.remove(str(scripts_dir))

    platforms = json.loads(
        (CUTFLOW_REPO / "skills" / "cutflow" / "templates" / "platforms.json").read_text("utf-8")
    )
    schema_v1 = json.loads(
        (CUTFLOW_REPO / "skills" / "cutflow" / "templates" / "project.schema.json").read_text("utf-8")
    )
    styles_dir = CUTFLOW_REPO / "skills" / "cutflow" / "templates" / "styles"
    return {
        "version": 1,
        "ratios": {k: list(v) for k, v in rs_common.RATIOS.items()},
        "platforms": platforms.get("platforms", {}),
        "fpsAllowed": schema_v1["properties"]["fps"]["enum"],
        "canvasAllowed": schema_v1["properties"]["canvas"]["properties"]["width"]["enum"],
        "styles": sorted(p.stem for p in styles_dir.glob("*.yaml")),
        "_doc": "AUTO-GENERATED by tools/gen_constants.py — DO NOT EDIT. 唯一来源: rs_common.RATIOS + platforms.json + project.schema(v1 enum)。Rust 侧经 cutforge-schema include_str! 消费;漂移由 --check 门禁(G3-5)阻断。",
    }


def render(constants: dict) -> str:
    return json.dumps(constants, ensure_ascii=False, indent=1, sort_keys=True) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="生成 schemas/constants.ratios.json(常量单源)")
    ap.add_argument("--check", action="store_true", help="只校验零漂移,不写文件")
    ap.add_argument("--json", action="store_true", help="输出结果协议 JSON")
    args = ap.parse_args(argv)

    try:
        constants = build_constants()
    except FileNotFoundError as exc:
        return _emit(False, "NO_ENV", str(exc), {}, args.json)
    except Exception as exc:  # noqa: BLE001
        return _emit(False, "INTERNAL", f"生成失败: {exc!r}", {}, args.json)

    text = render(constants)
    if args.check:
        if not OUT_PATH.exists():
            return _emit(False, "CONST_DRIFT", f"生成物不存在: {OUT_PATH}", {}, args.json)
        existing = OUT_PATH.read_text("utf-8")
        if existing != text:
            try:
                old, new = json.loads(existing), json.loads(text)
                diff = [k for k in set(old) | set(new) if old.get(k) != new.get(k)]
            except Exception:  # noqa: BLE001
                diff = ["<unparseable>"]
            return _emit(False, "CONST_DRIFT", f"常量漂移,键差异: {diff}(重新运行生成器)", {"diff": diff}, args.json)
        return _emit(True, "OK", "constants.ratios.json 与 rs_common.RATIOS + platforms.json 逐键相等(零漂移)",
                     {"keys": sorted(constants)}, args.json)
    OUT_PATH.write_text(text, encoding="utf-8", newline="\n")
    return _emit(True, "OK", f"已写入 {OUT_PATH}", {"path": str(OUT_PATH)}, args.json)


if __name__ == "__main__":
    sys.exit(main())
