#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""TS SDK 生成器(册七 T7.1/AC-7.1;ADR-0003「描述文件是生成物」同纪律)。

    python tools/gen_ts_sdk.py            # 生成 apps/sdk/cutforge.ts
    python tools/gen_ts_sdk.py --check    # 校验:0=一致;2=GEN_STALE(生成物过期)

单一真相源 = schemas/mcp-tools.json(工具契约):78 个工具各映射为一个类型化方法
(参数 interface 由 inputSchema 生成,snake→camel;枚举 → 字面量联合;嵌套对象 →
内联类型)。传输面零依赖:全局 fetch 打 `POST /api/v1/tools/<tool>`(ADR-0025 REST
面)+ 手写 SSE 解析订阅 `/api/v1/events`(浏览器/node ≥18/bun 通用,不依赖
EventSource)。生成物只含可剥离语法(type/interface/class,无 enum)——node
--experimental-strip-types(23.6 起默认)与 bun 可直跑,冒烟测试
tools/test_ts_sdk.mjs 对真 serve 验证 ≥10 个典型调用。
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO = Path(__file__).resolve().parents[1]
CONTRACT = REPO / "schemas" / "mcp-tools.json"
OUT = REPO / "apps" / "sdk" / "cutforge.ts"

HEADER = """\
// AUTO-GENERATED by tools/gen_ts_sdk.py ← schemas/mcp-tools.json —— 禁止手改
// 单一真相源 = schemas/mcp-tools.json({n_tools} 工具;改契约后重跑生成器,--check 拦漂移)
// 传输面:POST /api/v1/tools/<tool>(册七 T7.1/ADR-0025)+ GET /api/v1/events 订阅;
// 零依赖:全局 fetch + 手写 SSE 解析(浏览器 / node >=18 / bun 通用)。
/* eslint-disable */

"""


def camel(name: str) -> str:
    parts = re.split(r"[_\-]", name)
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def pascal(name: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[_\-]", name) if p)


def ts_type(schema: dict, indent: str = "") -> str:
    """JSON Schema → TS 类型(生成 SDK 面所需的最小子集;枚举 → 字面量联合)。"""
    if not isinstance(schema, dict):
        return "unknown"
    if "$ref" in schema:
        return "Record<string, unknown>"  # 契约内 $ref(fxEntry)以宽类型承载
    t = schema.get("type")
    if "enum" in schema:
        lits = " | ".join(
            json.dumps(v, ensure_ascii=False) if isinstance(v, str) else json.dumps(v)
            for v in schema["enum"]
        )
        return lits
    if isinstance(t, list):
        base = [x for x in t if x != "null"]
        nullable = " | null" if "null" in t else ""
        if base:
            return ts_type({**schema, "type": base[0]}, indent) + nullable
        return "unknown" + nullable
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "array":
        items = schema.get("items", {})
        return f"Array<{ts_type(items, indent)}>"
    if t == "object":
        props = schema.get("properties")
        if not props:
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        lines = ["{"]
        inner = indent + "  "
        for k, prop in props.items():
            opt = "" if k in required else "?"
            desc = (prop.get("description") or "").strip()
            if desc:
                lines.append(f"{inner}/** {desc} */")
            key = k if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", k) else json.dumps(k)
            lines.append(f"{inner}{key}{opt}: {ts_type(prop, inner)};")
        lines.append(indent + "}")
        return " ".join(lines[0:1] + lines[1:]) if False else "\n".join(lines)
    return "unknown"


def arg_interface(tool: dict) -> str:
    name = pascal(tool["name"]) + "Args"
    schema = tool.get("inputSchema", {})
    props = schema.get("properties", {})
    if not props:
        return f"export interface {name} {{ [k: string]: unknown; }}\n"
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for k, prop in props.items():
        opt = "" if k in required else "?"
        desc = (prop.get("description") or "").strip().replace("\n", " ")
        if desc:
            lines.append(f"  /** {desc} */")
        key = k if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", k) else json.dumps(k)
        lines.append(f"  {key}{opt}: {ts_type(prop, '  ')};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit(doc: dict) -> str:
    tools = doc["tools"]
    out = [HEADER.format(n_tools=len(tools))]
    out.append("""\
/** 结果协议 envelope(所有工具/别名端点的统一返回;HTTP 状态码由 code 确定性映射)。 */
export interface Envelope<T = Record<string, unknown>> {
  ok: boolean;
  code: string;
  ns: string;
  message: string;
  data: T;
}

/** 工具入参兜底形(泛型逃逸口;类型化方法见下方按工具生成的面)。 */
export type ToolArgs = Record<string, unknown>;

/** /api/v1/events 的一帧(SSE data 负载;ok/code/event/seq 老字段齐)。 */
export interface WorkspaceEvent {
  ok: boolean;
  code: string;
  event: string;
  seq: number;
  paths?: string[];
  kind?: string;
  runId?: string;
  state?: string;
  [k: string]: unknown;
}

export interface CutforgeOptions {
  /** 服务基址,如 http://127.0.0.1:8765(端口见 <工程>/.cutforge/session) */
  baseUrl: string;
  /** Bearer token(serve 启动时落盘 .cutforge/session;数据面必须持 token) */
  token: string;
  /** 绑定工程根:工具入参缺 root 时自动注入(工作区通道语义;可省) */
  root?: string;
  /** 自定义 fetch 实现(测试注入用;缺省全局 fetch) */
  fetchImpl?: typeof fetch;
}

/**
 * CutForge Editor API 类型化客户端(生成物;册七 T7.1)。
 * 与 /rpc 同一 dispatch 单表(三通道同源,工具集差异恒为 0)。
 */
export class CutforgeClient {
  private readonly baseUrl: string;
  private readonly token: string;
  private readonly root?: string;
  private readonly fetchImpl: typeof fetch;

  constructor(opts: CutforgeOptions) {
    this.baseUrl = opts.baseUrl.replace(/\\/$/, "");
    this.token = opts.token;
    this.root = opts.root;
    this.fetchImpl = opts.fetchImpl ?? fetch.bind(globalThis);
  }

  /** 统一工具入口:POST /api/v1/tools/<tool>(转发既有 dispatch 单表)。 */
  async call<T = Record<string, unknown>>(tool: string, args?: ToolArgs): Promise<Envelope<T>> {
    const merged: ToolArgs = { ...(args ?? {}) };
    if (merged["root"] === undefined && this.root !== undefined) {
      merged["root"] = this.root;
    }
    const res = await this.fetchImpl(`${this.baseUrl}/api/v1/tools/${encodeURIComponent(tool)}`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${this.token}` },
      body: JSON.stringify(merged),
    });
    return (await res.json()) as Envelope<T>;
  }

  /** 工具清单(GET /api/v1/tools;schemas/mcp-tools.json 单一真相源)。 */
  async listTools(): Promise<Envelope<{ tools: Array<{ name: string; kind: string; description: string }> }>> {
    const res = await this.fetchImpl(`${this.baseUrl}/api/v1/tools`, {
      headers: { Authorization: `Bearer ${this.token}` },
    });
    return (await res.json()) as Envelope<{ tools: Array<{ name: string; kind: string; description: string }> }>;
  }

  /** 事件流地址(SSE 用 EventSource / 手写解析皆可;token 经查询串)。 */
  eventsUrl(): string {
    return `${this.baseUrl}/api/v1/events?token=${encodeURIComponent(this.token)}`;
  }

  /**
   * 订阅工作区事件(SSE;零依赖手写解析,不依赖 EventSource)。
   * 返回退订函数(AbortController.abort)。`bye` 事件/流结束自动停。
   */
  async subscribeEvents(
    onEvent: (ev: WorkspaceEvent) => void,
    opts: { since?: number; signal?: AbortSignal } = {},
  ): Promise<() => void> {
    const ctrl = new AbortController();
    const onAbort = () => ctrl.abort();
    if (opts.signal) {
      if (opts.signal.aborted) {
        ctrl.abort();
      } else {
        opts.signal.addEventListener("abort", onAbort, { once: true });
      }
    }
    const url = `${this.eventsUrl()}${opts.since !== undefined ? `&since=${opts.since}` : ""}`;
    const res = await fetch(url, {
      headers: { Accept: "text/event-stream", Authorization: `Bearer ${this.token}` },
      signal: ctrl.signal,
    });
    if (!res.ok || !res.body) {
      throw new Error(`SSE 建立失败: HTTP ${res.status}`);
    }
    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buf = "";
    const pump = async (): Promise<void> => {
      for (;;) {
        const { done, value } = await reader.read();
        if (done) {
          return;
        }
        buf += decoder.decode(value, { stream: true });
        let idx: number;
        while ((idx = buf.indexOf("\\n\\n")) >= 0) {
          const frame = buf.slice(0, idx);
          buf = buf.slice(idx + 2);
          let ev = "message";
          const dataLines: string[] = [];
          for (const line of frame.split("\\n")) {
            if (line.startsWith(":")) {
              continue; // 心跳注释
            }
            if (line.startsWith("event:")) {
              ev = line.slice(6).trim();
            } else if (line.startsWith("data:")) {
              dataLines.push(line.slice(5).trim());
            }
          }
          if (!dataLines.length) {
            continue;
          }
          let data: WorkspaceEvent;
          try {
            data = JSON.parse(dataLines.join("\\n")) as WorkspaceEvent;
          } catch {
            continue;
          }
          onEvent(data);
          if (ev === "bye") {
            ctrl.abort();
            return;
          }
        }
      }
    };
    pump().catch((err) => {
      if (!ctrl.signal.aborted) {
        throw err;
      }
    });
    return () => {
      ctrl.abort();
      if (opts.signal) {
        opts.signal.removeEventListener("abort", onAbort);
      }
    };
  }

  // ---- 工具方法(78 个;由 schemas/mcp-tools.json 生成) ----
""")

    for t in tools:
        name = t["name"]
        kind = t.get("kind", "?")
        desc = (t.get("description") or "").strip().replace("\n", " ")
        iface = pascal(name) + "Args"
        schema = t.get("inputSchema", {})
        has_props = bool(schema.get("properties"))
        method = camel(name)
        if name == "capability_matrix":
            out.append(
                f"  /** {desc} */\n"
                f"  {method}(): Promise<Envelope> {{\n"
                f"    return this.call(\"{name}\");\n"
                f"  }}\n"
            )
        elif has_props:
            out.append(
                f"  /** {desc}(kind: {kind}) */\n"
                f"  {method}(args: {iface}): Promise<Envelope> {{\n"
                f"    return this.call(\"{name}\", args);\n"
                f"  }}\n"
            )
        else:
            out.append(
                f"  /** {desc}(kind: {kind}) */\n"
                f"  {method}(args?: {iface}): Promise<Envelope> {{\n"
                f"    return this.call(\"{name}\", args);\n"
                f"  }}\n"
            )
    out.append("}\n")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description="TS SDK 生成器(mcp-tools.json 单一真相源)")
    ap.add_argument("--check", action="store_true", help="校验生成物与契约一致(漂移退出码 2)")
    a = ap.parse_args()

    doc = json.loads(CONTRACT.read_text(encoding="utf-8"))
    rendered = emit(doc)

    if a.check:
        if not OUT.is_file():
            print(f"[GEN_STALE] {OUT} 不存在;先跑 python tools/gen_ts_sdk.py")
            return 2
        if OUT.read_text(encoding="utf-8") != rendered:
            print("[GEN_STALE] apps/sdk/cutforge.ts 与契约漂移(先跑 python tools/gen_ts_sdk.py)")
            return 2
        n = len(doc["tools"])
        methods = rendered.count("this.call(\"")
        print(f"[OK] TS SDK 生成物零漂移:{n} 工具,{methods} 个类型化调用面")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"[OK] TS SDK 已生成:{OUT}(相对仓库根;{len(doc['tools'])} 工具)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
