#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Python 校验器生成器(计划书 3.8,ADR-0034)。

    python tools/schema_gen.py [--check] [--json]

读取 schemas/*.json(唯一手写契约),生成 tools/_generated/cf_validate.py:
纯标准库、自包含(draft-07 子集引擎 + 五份 schema 内嵌 + project v1→v2 迁移器)。
生成物文件头带 AUTO-GENERATED,禁止手工编辑;改动契约只能改 schema 再重新生成。

退出码:0 通过 / 2 生成物缺失或过期 / 3 前置缺失 / 4 内部错误。
"""
from __future__ import annotations

import argparse
import json
import sys
import sys
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = REPO_ROOT / "schemas"
OUT_PATH = REPO_ROOT / "tools" / "_generated" / "cf_validate.py"

SCHEMA_FILES = [
    "project", "wordline", "cutlist", "notes", "oplog",
]

# 引擎模板:{SCHEMAS} 处注入五份 schema 的 JSON 字面量。
# 生成物必须纯标准库:不引 jsonschema,把约束编译为本模块内的子集校验器。
TEMPLATE = '''# -*- coding: utf-8 -*-
# AUTO-GENERATED by tools/schema_gen.py — DO NOT EDIT.
# 修改契约请编辑 schemas/*.json 后重新生成(计划书 3.8:生成物不得手工编辑)。
from __future__ import annotations

import argparse
import copy
import json
import re
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

SCHEMAS = json.loads(r{SQS}{SCHEMAS}{SQS})

NAMES = tuple(SCHEMAS)


def _resolve(schema: dict, root: dict) -> dict:
    while "$ref" in schema:
        ref = schema["$ref"]
        if not ref.startswith("#/"):
            raise ValueError(f"不支持的外部引用: {{ref}}")
        node = root
        for part in ref[2:].split("/"):
            node = node[part.replace("~1", "/").replace("~0", "~")]
        schema = node
    return schema


def _check_type(types: list[str], data) -> bool:
    if data is None:
        return "null" in types
    types = [t for t in types if t != "null"] or types
    if types == ["integer"]:
        return isinstance(data, int) and not isinstance(data, bool)
    if "integer" in types:
        return (isinstance(data, int) and not isinstance(data, bool)) or (
            "number" in types and isinstance(data, float))
    if "number" in types:
        return isinstance(data, (int, float)) and not isinstance(data, bool)
    if "string" in types:
        return isinstance(data, str)
    if "boolean" in types:
        return isinstance(data, bool)
    if "object" in types:
        return isinstance(data, dict)
    if "array" in types:
        return isinstance(data, list)
    if "null" in types:
        return data is None
    return False


def validate(schema_name: str, data, path: str = "$") -> list[str]:
    """返回错误列表;空列表 = 通过。支持 draft-07 子集 + 两个 x- 断言。"""
    root = SCHEMAS[schema_name]
    return _validate(root, root, data, path)


def _validate(schema: dict, root: dict, data, path: str) -> list[str]:
    errors: list[str] = []
    schema = _resolve(schema, root)

    if "const" in schema and data != schema["const"]:
        errors.append(f"{{path}}: const 期望 {{schema['const']!r}} 实际 {{data!r}}")
        return errors
    if "enum" in schema and data not in schema["enum"]:
        errors.append(f"{{path}}: enum {{schema['enum']!r}} 不含 {{data!r}}")
        return errors

    t = schema.get("type")
    if t is not None:
        types = t if isinstance(t, list) else [t]
        if not _check_type(types, data):
            errors.append(f"{{path}}: type 期望 {{types}} 实际 {{type(data).__name__}}")
            return errors

    if isinstance(data, bool):
        return errors  # bool 是 int 子类,后续数值断言不适用

    if isinstance(data, (int, float)):
        if "minimum" in schema and data < schema["minimum"]:
            errors.append(f"{{path}}: minimum {{schema['minimum']}} 实际 {{data}}")
        if "maximum" in schema and data > schema["maximum"]:
            errors.append(f"{{path}}: maximum {{schema['maximum']}} 实际 {{data}}")
        if "exclusiveMinimum" in schema and data <= schema["exclusiveMinimum"]:
            errors.append(f"{{path}}: exclusiveMinimum {{schema['exclusiveMinimum']}} 实际 {{data}}")

    if isinstance(data, str):
        if "minLength" in schema and len(data) < schema["minLength"]:
            errors.append(f"{{path}}: minLength {{schema['minLength']}} 实际长度 {{len(data)}}")
        if "maxLength" in schema and len(data) > schema["maxLength"]:
            errors.append(f"{{path}}: maxLength {{schema['maxLength']}} 实际长度 {{len(data)}}")
        if "pattern" in schema and re.search(schema["pattern"], data) is None:
            errors.append(f"{{path}}: pattern {{schema['pattern']!r}} 不匹配 {{data!r}}")

    if isinstance(data, list):
        if "minItems" in schema and len(data) < schema["minItems"]:
            errors.append(f"{{path}}: minItems {{schema['minItems']}} 实际 {{len(data)}}")
        if "maxItems" in schema and len(data) > schema["maxItems"]:
            errors.append(f"{{path}}: maxItems {{schema['maxItems']}} 实际 {{len(data)}}")
        item = schema.get("items")
        if isinstance(item, dict):
            for i, el in enumerate(data):
                errors.extend(_validate(item, root, el, f"{{path}}[{{i}}]"))

    if isinstance(data, dict):
        for k in schema.get("required", []):
            if k not in data:
                errors.append(f"{{path}}: 缺必填键 '{{k}}'")
        props = schema.get("properties", {{}})
        for k, v in data.items():
            if k in props:
                errors.extend(_validate(props[k], root, v, f"{{path}}.{{k}}"))
            elif schema.get("additionalProperties") is False:
                errors.append(f"{{path}}: additionalProperties=false 拒绝多余键 '{{k}}'")

    # ---- 自定义跨字段断言(计划书 3.5:SKILL Hard Rule 3 进契约) ----
    if schema.get("x-removeRequiresGuardOk") and isinstance(data, dict) and data.get("action") == "remove":
        guard = data.get("guard")
        if not isinstance(guard, dict) or not guard:
            errors.append(f"{{path}}: action=remove 但 guard 为空(guard_passed 视为未过)")
        else:
            ok = guard.get("okByReason") if "okByReason" in guard else guard.get("ok")
            if ok is not True:
                errors.append(f"{{path}}: action=remove 但 guard 判定 ok={{ok!r}}")
            if guard.get("wordClipped") is True:
                errors.append(f"{{path}}: action=remove 但 wordClipped=true(任何 reason 下硬失败)")
    if schema.get("x-keepCoversTimeline") and isinstance(data, dict):
        keep = data.get("keep")
        total = data.get("srcTotalMs")
        if isinstance(keep, list) and isinstance(total, int):
            cur = 0
            ok_order = True
            for seg in keep:
                if (not isinstance(seg, list) or len(seg) != 2
                        or not all(isinstance(x, int) for x in seg) or seg[0] < cur or seg[1] < seg[0]):
                    ok_order = False
                    break
                cur = seg[1]
            if not ok_order:
                errors.append(f"{{path}}: keep 区间无序/重叠/非法")
            elif cur != total:
                errors.append(f"{{path}}: keep 覆盖到 {{cur}} ≠ srcTotalMs {{total}}")
    return errors


TRACK_LETTER = {{"video": "V", "audio": "A", "text": "T"}}


def migrate_project_v1_to_v2(doc: dict) -> dict:
    """v1→v2 迁移(计划书 3.3):幂等——对同一输入迁移两次,结果相等。"""
    if not isinstance(doc, dict):
        raise ValueError("project 文档必须是 object")
    out = copy.deepcopy(doc)
    out.setdefault("schemaVersion", "2.0.0")
    out.setdefault("backends", ["ffmpeg"])
    out.setdefault("notes", "notes.json")
    for ti, track in enumerate(out.get("tracks", [])):
        tid = track.get("id") or (
            f"{{TRACK_LETTER.get(track.get('kind', ''), 'X')}}{{ti + 1}}")
        track["id"] = tid
        for ci, clip in enumerate(track.get("clips", [])):
            clip["id"] = clip.get("id") or f"{{tid}}-{{ci + 1:03d}}"
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="CutFlow/CutForge 契约校验器(生成物)")
    ap.add_argument("schema", choices=NAMES)
    ap.add_argument("file", help="待校验 JSON 文件")
    ap.add_argument("--migrate", action="store_true",
                    help="project 先走 v1→v2 迁移再校验(不写回原文件)")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args(argv)

    p = Path(args.file)
    if not p.exists():
        env = {{"ok": False, "code": "NO_ENV", "message": f"文件不存在: {{p}}", "data": {{}}}}
        print(json.dumps(env, ensure_ascii=False) if args.json else env["message"])
        return 3
    try:
        doc = json.loads(p.read_text("utf-8"))
        target = doc
        if args.migrate and args.schema == "project":
            target = migrate_project_v1_to_v2(doc)
        errors = validate(args.schema, target)
    except Exception as exc:  # noqa: BLE001
        env = {{"ok": False, "code": "INTERNAL", "message": repr(exc), "data": {{}}}}
        print(json.dumps(env, ensure_ascii=False, indent=2) if args.json else env["message"])
        return 4
    env = {{"ok": not errors, "code": "OK" if not errors else "SCHEMA_INVALID",
           "message": "通过" if not errors else f"{{len(errors)}} 处校验失败",
           "data": {{"schema": args.schema, "file": str(p), "errors": errors}}}}
    if args.json:
        print(json.dumps(env, ensure_ascii=False, indent=2))
    else:
        print(env["message"])
        for e in errors[:20]:
            print("  -", e)
    return 0 if not errors else 2


if __name__ == "__main__":
    sys.exit(main())
'''


def build_generated() -> str:
    schemas = {}
    for name in SCHEMA_FILES:
        p = SCHEMA_DIR / f"{name}.schema.json"
        if not p.exists():
            raise FileNotFoundError(f"schema 缺失: {p}")
        schemas[name] = json.loads(p.read_text("utf-8"))
    payload = json.dumps(schemas, ensure_ascii=False, sort_keys=True)
    if "'''" in payload:
        # 原始三引号字符串无法安全承载;契约描述里出现 ''' 属于契约缺陷,拒绝生成
        raise ValueError("schema 描述包含 ''' 字符,请改写描述后再生成")
    return TEMPLATE.format(SCHEMAS=payload, SQS="'''")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="生成 tools/_generated/cf_validate.py")
    ap.add_argument("--check", action="store_true", help="只校验生成物未过期")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args(argv)

    def emit(ok: bool, code: str, msg: str, data: dict) -> int:
        env = {"ok": ok, "code": code, "message": msg, "data": data}
        print(json.dumps(env, ensure_ascii=False, indent=2) if args.json else msg)
        return {"OK": 0, "GEN_STALE": 2, "NO_ENV": 3, "INTERNAL": 4}.get(code, 4)

    try:
        text = build_generated()
    except FileNotFoundError as exc:
        return emit(False, "NO_ENV", str(exc), {})
    except Exception as exc:  # noqa: BLE001
        return emit(False, "INTERNAL", f"生成失败: {exc!r}", {})

    if args.check:
        if not OUT_PATH.exists():
            return emit(False, "GEN_STALE", f"生成物不存在: {OUT_PATH}", {})
        if OUT_PATH.read_text("utf-8") != text:
            return emit(False, "GEN_STALE", "生成物过期(schema 已变,重新生成)", {}, )
        return emit(True, "OK", "生成物与 schema 一致", {"path": str(OUT_PATH)})
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(text, encoding="utf-8", newline="\n")
    return emit(True, "OK", f"已写入 {OUT_PATH}", {"path": str(OUT_PATH)})


if __name__ == "__main__":
    sys.exit(main())
